#!/usr/bin/env python3
"""Curated Related Archives data for organization pages."""

from __future__ import annotations

ORG_OVERRIDES: dict[str, list[tuple[str, str, str]]] = {
    "techno-union": [
        ("Character", "General Grievous", "characters/general-grievous"),
        ("Jedi", "Anakin Skywalker", "jedi/anakin-skywalker"),
        ("Jedi", "Obi-Wan Kenobi", "jedi/obi-wan-kenobi"),
        ("Sith", "Darth Tyranus", "sith/darth-tyranus"),
        ("Planet", "Skako", "planet/skako"),
        ("Planet", "Geonosis", "planet/geonosis"),
        ("Battle", "First Battle of Geonosis", "wars-conflicts/battles/first-battle-of-geonosis"),
        ("Faction", "Confederacy of Independent Systems", "factions/confederacy"),
    ],
    "intergalactic-banking-clan": [
        ("Character", "Nute Gunray", "characters/nute-gunray"),
        ("Character", "Rush Clovis", "characters/rush-clovis"),
        ("Jedi", "Obi-Wan Kenobi", "jedi/obi-wan-kenobi"),
        ("Planet", "Muunilinst", "planet/muunilinst"),
        ("Planet", "Mygeeto", "planet/mygeeto"),
        ("Battle", "Battle of Muunilinst", "wars-conflicts/battles/battle-of-muunilinst"),
        ("Faction", "Confederacy of Independent Systems", "factions/confederacy"),
    ],
    "commerce-guild": [
        ("Character", "Padmé Amidala", "characters/padme-amidala"),
        ("Jedi", "Ahsoka Tano", "jedi/ahsoka-tano"),
        ("Jedi", "Anakin Skywalker", "jedi/anakin-skywalker"),
        ("Planet", "Castell", "planet/castell"),
        ("Planet", "Felucia", "planet/felucia"),
        ("Faction", "Confederacy of Independent Systems", "factions/confederacy"),
    ],
    "corporate-alliance": [
        ("Character", "Padmé Amidala", "characters/padme-amidala"),
        ("Jedi", "Mace Windu", "jedi/mace-windu"),
        ("Sith", "Darth Tyranus", "sith/darth-tyranus"),
        ("Battle", "First Battle of Geonosis", "wars-conflicts/battles/first-battle-of-geonosis"),
        ("Faction", "Confederacy of Independent Systems", "factions/confederacy"),
    ],
    "retail-caucus": [
        ("Character", "Onaconda Farr", "characters/onaconda-farr"),
        ("Character", "Padmé Amidala", "characters/padme-amidala"),
        ("Character", "General Grievous", "characters/general-grievous"),
        ("Faction", "Confederacy of Independent Systems", "factions/confederacy"),
    ],
    "pyke-syndicate": [
        ("Bounty Hunter", "Cad Bane", "bounty-hunters/cad-bane"),
        ("Character", "Han Solo", "characters/han-solo"),
        ("Character", "Chewbacca", "characters/chewbacca"),
        ("Jedi", "Obi-Wan Kenobi", "jedi/obi-wan-kenobi"),
        ("Jedi", "Anakin Skywalker", "jedi/anakin-skywalker"),
        ("Planet", "Oba Diah", "planet/oba-diah"),
        ("Planet", "Kessel", "planet/kessel"),
        ("Settlement", "Kessel", "settlements/kessel"),
        ("Military unit", "Pyke Syndicate Forces", "military-units/other/army/pyke-syndicate-forces"),
        ("Faction", "Hutts", "factions/hutts"),
    ],
    "black-sun": [
        ("Sith", "Darth Maul", "sith/darth-maul"),
        ("Character", "Boba Fett", "characters/boba-fett"),
        ("Character", "Fennec Shand", "characters/fennec-shand"),
        ("Jedi", "Obi-Wan Kenobi", "jedi/obi-wan-kenobi"),
        ("Jedi", "Ahsoka Tano", "jedi/ahsoka-tano"),
        ("Planet", "Mustafar", "mustafar"),
        ("Settlement", "Nar Shaddaa", "settlements/nar-shaddaa"),
    ],
    "crimson-dawn": [
        ("Sith", "Darth Maul", "sith/darth-maul"),
        ("Character", "Dryden Vos", "characters/dryden-vos"),
        ("Character", "Qi'ra", "characters/qira"),
        ("Character", "Han Solo", "characters/han-solo"),
        ("Character", "Lando Calrissian", "characters/lando-calrissian"),
        ("Planet", "Corellia", "planet/corellia"),
        ("Planet", "Dathomir", "planet/dathomir"),
        ("Organization", "Pyke Syndicate", "organizations/pyke-syndicate"),
    ],
    "inquisitorius": [
        ("Sith", "The Grand Inquisitor", "sith/grand-inquisitor"),
        ("Sith", "Darth Vader", "sith/darth-vader"),
        ("Sith", "Darth Sidious", "sith/darth-sidious"),
        ("Sith", "Second Sister", "sith/second-sister"),
        ("Sith", "Ninth Sister", "sith/ninth-sister"),
        ("Jedi", "Kanan Jarrus", "jedi/kanan-jarrus"),
        ("Jedi", "Ezra Bridger", "jedi/ezra-bridger"),
        ("Jedi", "Ahsoka Tano", "jedi/ahsoka-tano"),
        ("Battle", "Jedi Purge", "wars-conflicts/battles/jedi-purge"),
        ("Planet", "Coruscant", "coruscant"),
        ("Planet", "Mustafar", "mustafar"),
        ("Faction", "Galactic Empire", "factions/empire"),
    ],
    "mining-guild": [
        ("Character", "Grand Moff Tarkin", "characters/grand-moff-tarkin"),
        ("Character", "Agent Kallus", "characters/agent-kallus"),
        ("Character", "Hera Syndulla", "characters/hera-syndulla"),
        ("Character", "Sabine Wren", "characters/sabine-wren"),
        ("Faction", "Galactic Empire", "factions/empire"),
    ],
    "smuggler-guilds": [
        ("Character", "Han Solo", "characters/han-solo"),
        ("Character", "Lando Calrissian", "characters/lando-calrissian"),
        ("Character", "Hondo Ohnaka", "characters/hondo-ohnaka"),
        ("Bounty Hunter", "Cad Bane", "bounty-hunters/cad-bane"),
        ("Settlement", "Nar Shaddaa", "settlements/nar-shaddaa"),
        ("Planet", "Corellia", "planet/corellia"),
        ("Directory", "Bounty Hunters", "all-bounty-hunters"),
    ],
    "corporate-blocs": [
        ("Character", "Nute Gunray", "characters/nute-gunray"),
        ("Character", "Padmé Amidala", "characters/padme-amidala"),
        ("Character", "Rush Clovis", "characters/rush-clovis"),
        ("Faction", "Trade Federation", "factions/trade-federation"),
        ("Organization", "Trade Federation Directorate", "organizations/trade-federation-directorate"),
        ("Organization", "InterGalactic Banking Holding", "organizations/intergalactic-banking-holding"),
    ],
    "crime-families": [
        ("Character", "Jabba the Hutt", "characters/jabba-the-hutt"),
        ("Character", "Boba Fett", "characters/boba-fett"),
        ("Jedi", "Luke Skywalker", "jedi/luke-skywalker"),
        ("Character", "Leia Organa", "characters/leia-organa"),
        ("Planet", "Nal Hutta", "planet/nal-hutta"),
        ("Planet", "Tatooine", "tatooine"),
        ("Faction", "Hutts", "factions/hutts"),
    ],
    "spice-runners-guild": [
        ("Character", "Han Solo", "characters/han-solo"),
        ("Character", "Chewbacca", "characters/chewbacca"),
        ("Character", "Qi'ra", "characters/qira"),
        ("Organization", "Smuggler Guilds", "organizations/smuggler-guilds"),
        ("Organization", "Pyke Syndicate", "organizations/pyke-syndicate"),
        ("Planet", "Kessel", "planet/kessel"),
        ("Settlement", "Kessel", "settlements/kessel"),
    ],
    "corellian-smuggler-guild": [
        ("Character", "Han Solo", "characters/han-solo"),
        ("Character", "Qi'ra", "characters/qira"),
        ("Character", "Lando Calrissian", "characters/lando-calrissian"),
        ("Character", "Wedge Antilles", "characters/wedge-antilles"),
        ("Organization", "Smuggler Guilds", "organizations/smuggler-guilds"),
        ("Planet", "Corellia", "planet/corellia"),
    ],
    "hutt-smuggling-rings": [
        ("Character", "Jabba the Hutt", "characters/jabba-the-hutt"),
        ("Character", "Han Solo", "characters/han-solo"),
        ("Character", "Boba Fett", "characters/boba-fett"),
        ("Character", "Din Djarin", "characters/din-djarin"),
        ("Organization", "Smuggler Guilds", "organizations/smuggler-guilds"),
        ("Faction", "Hutts", "factions/hutts"),
        ("Planet", "Nal Hutta", "planet/nal-hutta"),
    ],
    "desilijic-kajidic": [
        ("Character", "Jabba the Hutt", "characters/jabba-the-hutt"),
        ("Character", "Bib Fortuna", "characters/bib-fortuna"),
        ("Character", "Boba Fett", "characters/boba-fett"),
        ("Jedi", "Luke Skywalker", "jedi/luke-skywalker"),
        ("Character", "Leia Organa", "characters/leia-organa"),
        ("Organization", "Crime Families", "organizations/crime-families"),
        ("Planet", "Tatooine", "tatooine"),
    ],
    "besadii-kajidic": [
        ("Character", "Han Solo", "characters/han-solo"),
        ("Character", "Leia Organa", "characters/leia-organa"),
        ("Organization", "Crime Families", "organizations/crime-families"),
        ("Planet", "Nal Hutta", "planet/nal-hutta"),
        ("Planet", "Kessel", "planet/kessel"),
        ("Faction", "Hutts", "factions/hutts"),
    ],
    "black-sun-vigo-council": [
        ("Sith", "Darth Maul", "sith/darth-maul"),
        ("Character", "Boba Fett", "characters/boba-fett"),
        ("Organization", "Black Sun", "organizations/black-sun"),
        ("Organization", "Crime Families", "organizations/crime-families"),
        ("Planet", "Mustafar", "mustafar"),
    ],
    "trade-federation-directorate": [
        ("Character", "Nute Gunray", "characters/nute-gunray"),
        ("Character", "Padmé Amidala", "characters/padme-amidala"),
        ("Jedi", "Obi-Wan Kenobi", "jedi/obi-wan-kenobi"),
        ("Jedi", "Anakin Skywalker", "jedi/anakin-skywalker"),
        ("Organization", "Corporate Blocs", "organizations/corporate-blocs"),
        ("Faction", "Trade Federation", "factions/trade-federation"),
        ("Planet", "Naboo", "naboo"),
        ("Battle", "Battle of Naboo", "wars-conflicts/battles/battle-of-naboo"),
    ],
    "intergalactic-banking-holding": [
        ("Character", "Rush Clovis", "characters/rush-clovis"),
        ("Character", "Padmé Amidala", "characters/padme-amidala"),
        ("Jedi", "Anakin Skywalker", "jedi/anakin-skywalker"),
        ("Organization", "Corporate Blocs", "organizations/corporate-blocs"),
        ("Organization", "InterGalactic Banking Clan", "organizations/intergalactic-banking-clan"),
        ("Planet", "Muunilinst", "planet/muunilinst"),
        ("Planet", "Scipio", "planet/scipio"),
    ],
}

FACTION_LABELS: dict[str, tuple[str, str, str]] = {
    "confederacy": ("Faction", "Confederacy of Independent Systems", "factions/confederacy"),
    "empire": ("Faction", "Galactic Empire", "factions/empire"),
}
